FROM balenalib/intel-nuc-debian

RUN apt-get update && apt-get install -y curl wget build-essential libelf-dev awscli bc flex libssl-dev python bison
COPY . /usr/src/app
WORKDIR /usr/src/app

ENV VERSION '2.32.0+rev4.prod'
RUN BALENA_MACHINE_NAME=intel-nuc ./build.sh build --device intel-nuc --os-version "$VERSION" --src example_module

CMD ./run.sh
